src/DemoDI/Models/ErrorViewModel.cs
using System;

namespace DemoDI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/DemoDI/Controllers/FromServicesController.cs
using DemoDI.Cases;
using Microsoft.AspNetCore.Mvc;

namespace DemoDI.Controllers
{
    public class FromServicesController : Controller
    {
        public void Index([FromServices] IClientServices clientServices)
        {
            clientServices.AddClient(new Client());
        }
    }
}

src/DemoDI/Controllers/GenericController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DemoDI.Cases;
using Microsoft.AspNetCore.Mvc;

namespace DemoDI.Controllers
{
    public class GenericController : Controller
    {
        private readonly IGenericRepository<Client> _clientRepository;

        public GenericController(IGenericRepository<Client> clientRepository)
        {
            _clientRepository = clientRepository;
        }

        public void Index()
        {
            _clientRepository.Add(new Client());
        }
    }
}

src/DemoDI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DemoDI.Models;

namespace DemoDI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/DemoDI/Controllers/LifecycleController.cs
using System;
using DemoDI.Cases;
using Microsoft.AspNetCore.Mvc;

namespace DemoDI.Controllers
{
    public class LifecycleController : Controller
    {
        public OperationService OperacaoService { get; }
        public OperationService OperacaoService2 { get; }

        public LifecycleController(OperationService operacaoService, OperationService operacaoService2)
        {
            OperacaoService = operacaoService;
            OperacaoService2 = operacaoService2;
        }

        public string Index()
        {
            return
                "First instace: " + Environment.NewLine +
                OperacaoService.Transient.OperationId + Environment.NewLine +
                OperacaoService.Scoped.OperationId + Environment.NewLine +
                OperacaoService.Singleton.OperationId + Environment.NewLine +
                OperacaoService.SingletonInstance.OperationId + Environment.NewLine +

                Environment.NewLine +
                Environment.NewLine +

                "Second instace: " + Environment.NewLine +
                OperacaoService2.Transient.OperationId + Environment.NewLine +
                OperacaoService2.Scoped.OperationId + Environment.NewLine +
                OperacaoService2.Singleton.OperationId + Environment.NewLine +
                OperacaoService2.SingletonInstance.OperationId + Environment.NewLine;
        }
    }
}

src/DemoDI/Controllers/MultipleClassesController.cs
using System;
using DemoDI.Cases;
using Microsoft.AspNetCore.Mvc;

namespace DemoDI.Controllers
{
    public class MultipleClassesController : Controller
    {
        private readonly Func<string, IService> _serviceAcessor;

        public MultipleClassesController(Func<string, IService> serviceAcessor)
        {
            _serviceAcessor = serviceAcessor;
        }

        public string Index()
        {
            return _serviceAcessor("A").Return();
            //return _serviceAcessor("B").Return();
            //return _serviceAcessor("C").Return();
        }
    }
}

src/DemoDI/Controllers/RealLifeController.cs
using DemoDI.Cases;
using Microsoft.AspNetCore.Mvc;

namespace DemoDI.Controllers
{
    public class RealLifeController : Controller
    {
        private readonly IClientServices _clientServices;

        public RealLifeController(IClientServices clientServices)
        {
            _clientServices = clientServices;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        public void Index()
        {
            _clientServices.AddClient(new Client());
        }
    }
}

src/DemoDI/Controllers/ServiceLocator2Controller.cs
using System;
using DemoDI.Cases;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;

namespace DemoDI.Controllers
{
    public class ServiceLocator2Controller : Controller
    {
        public void Index([FromServices] IServiceProvider serviceProvider)
        {
            // return null if it's not registered
            serviceProvider.GetRequiredService<IClientServices>().AddClient(new Client());
        }
    }
}

src/DemoDI/Controllers/ServiceLocatorController.cs
using System;
using DemoDI.Cases;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;

namespace DemoDI.Controllers
{
    public class ServiceLocatorController : Controller
    {
        private readonly IServiceProvider _serviceProvider;

        public ServiceLocatorController(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        public void Index()
        {
            // return null if it's not registered
            _serviceProvider.GetRequiredService<IClientServices>().AddClient(new Client());
        }
    }
}

src/DemoDI/Views/Home/Index.cshtml
@{
        Layout = null;
    }
    <html>
    <head>
        <title>@ViewData["Title"] - DemoDI</title>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </head>
    <body>

        <header>
            <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoDI</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="RealLife" asp-action="Index">Real Life</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Lifecycle" asp-action="Index">Lifecycle</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Generic" asp-action="Index">Generics</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="FromServices" asp-action="Index">From Services</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="ServiceLocator" asp-action="Index">Service Locator</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="ServiceLocator2" asp-action="Index">Service Locator 2</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="MultipleClasses" asp-action="Index">Multiple Classes</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    </body>
    </html>

src/DemoDI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoDI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoDI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - DemoDI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>